name: CI

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Backend tests
        run: docker compose --profile tools run --rm --build backend-test
      - name: Cleanup
        if: always()
        run: docker compose --profile tools down

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Frontend tests
        run: docker compose --profile tools run --rm --build nextjs-test
      - name: Frontend lint
        run: docker compose --profile tools run --rm --build nextjs-lint
      - name: Cleanup
        if: always()
        run: docker compose --profile tools down

  build-check:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -f backend/Dockerfile -t backend-check ./backend
      - name: Build frontend image
        run: docker build -f frontend/Dockerfile -t frontend-check ./frontend
      - name: Scan backend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: backend-check
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      - name: Scan frontend image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: frontend-check
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

